version: "3"
services:
  net-core-tool-service:
    build: NetCoreToolService
    environment:
      DOTNET_ENVIRONMENT: Development
    ports:
      - "1922:80"
  initializr-config-server:
    build: InitializrConfigServer
    volumes:
      - ./InitializrConfig:/config
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS: file:///config
    ports:
      - "8888:80"
  initializr-api:
    build: InitializrApi
    entrypoint: ["./wait-for-it", "initializr-config-server:80", "--", "dotnet", "Steeltoe.InitializrApi.dll"]
    environment:
      DOTNET_ENVIRONMENT: "Docker"
    ports:
      - "1920:80"
  initializr-web:
    build: InitializrWeb
  initializr-ingress:
    build: InitializrIngress
    ports:
      - "8080:80"
  initializr-cli:
    build: InitializrCli
