version: "3"
services:
  initializr-config-server:
    build: InitializrConfigServer
    volumes:
      - ./InitializrConfig:/config
    environment:
      SERVER_PORT: 80
      # comment out following 2 lines to use GitHub config
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS: file:///config
    ports:
      - "8888:80"
  net-core-tool-service:
    build: NetCoreToolService
    environment:
      DOTNET_ENVIRONMENT: Docker
    ports:
      - "1922:80"
  initializr-service:
    build: InitializrService
    entrypoint:
      - "./wait-for-it"
      - "initializr-config-server:80"
      - "--"
      - "dotnet"
      - "Steeltoe.InitializrService.dll"
    environment:
      DOTNET_ENVIRONMENT: Docker
    ports:
      - "1920:80"
  initializr-web:
    build: InitializrWeb
  initializr-ingress:
    build: InitializrIngress
    ports:
      - "8080:80"
